version: '3'
#aqui se declara el uso 
services:
    #nombre del servicio
    flask:
      build: .
          #context: cashman
          #metodo lanzador
          #dockerfile: Dockerfile
      #esto lanzara nuestro framework    
      command: ./bootstrap.sh
      container_name: cashman
      image: digitalocean.com/flask-python:3
      restart: unless-stopped
      environment:
        APP_ENV: "prod"
        APP_DEBUG: "False"
        APP_PORT: 5000
        #parametros para la conexion con la db en variables de entorno
        MONGODB_DATABASE: cashman
        MONGODB_USERNAME: diego
        MONGODB_PASSWORD: abc123
        MONGODB_HOSTNAME: mongodb
      #direccion del la carpeta main
      volumes:
        - ./:/cashman     
      depends_on:
        - mongodb
      networks:
        - frontend
        - backend
    #servicio para el proxy nginx
    webserver:
      build:
          context: nginx
          #dockerfile: Dockerfile
      image: nginx:latest #digitalocean.com/webserver:latest
      container_name: webserver
      restart: unless-stopped
      environment:
          APP_ENV: "prod"
          APP_NAME: "webserver"
          APP_DEBUG: "false"
          SERVICE_NAME: "webserver"
      #puerto de escucha
      ports:
          - "8000:80"
      volumes:
          - nginxdata:/var/log/nginx
      depends_on:
        - flask
      networks:
        - frontend

    #servicio de mongodb
    mongodb:
      image: mongo
      volumes:
          - mongodbdata:/data/db
      networks:
        - backend

#en esta parte se definen basicamente por donde transitaran los datos de las variables a la db
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
  nginxdata:
    driver: local